# Generated by Django 3.2.5 on 2022-06-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('type', models.TextField(choices=[('Vehicle', 'Vehicle'), ('Cargo', 'Cargo'), ('Goods', 'Goods')])),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
