# Generated by Django 3.2.5 on 2022-06-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_cargo_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
